feat(#39): Create a room
CSU-Booking-Platform/application pull request #199
Opened 2020-11-21 19:29 UTC by joeyabou

**IMPORTANT: Please do not create a Pull Request without creating an issue first.**
Please provide enough information so that others can review your pull request:

Explain the **details** for making this change. What existing problem does the pull request solve?

### Test plan (required)
Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes UI.

### Closing issues
List all issues this PR resolves.
- closes #39 

### Pre-Merge checklist 
Complete these items before requesting reviews
- [ ] Static Analysis Rules Validated
- [ ] All commits follow naming conventions 

### Sub-tasks Checklist
- [ ] UI Implementation
- [ ] UI Test
- [ ] Backend Implementation
- [ ] Backend Tests
- [ ] Integration Tests
- [ ] System Tests

2020-11-22 22:43 UTC, alexstojda requested changes
Some minor things to fix :)

2020-11-22 22:43 UTC, alexstojda commented on tests/Javascript/Pages/Admin/Rooms/CreateRoom.spec.js
> +test('createPermission when no form errors', () => {
```suggestion
test('createRoom when no form errors', () => {
```

2020-11-22 22:43 UTC, alexstojda commented on tests/Javascript/Pages/Admin/Rooms/CreateRoom.spec.js
> +test('createPermission when form errors', () => {
```suggestion
test('createRoom when form errors', () => {
```

2020-11-22 22:43 UTC, alexstojda commented on app/Http/Controllers/RoomController.php
> +        return back()->with('flash', ['we good']);
```suggestion
        return back();
```

We can remove the flash since its never used in the frontend.

2020-11-23 00:09 UTC, danseremet approved these changes
Looks good to me, I think this should reference https://github.com/csu-booking-platform/application/issues/53 and not #39 
@alexstojda right?

2020-11-25 00:34 UTC, alexstojda approved these changes

2020-11-25 01:14 UTC, danseremet approved these changes

2020-11-25 01:15 UTC, merged