feat(#212) Navbar Component
CSU-Booking-Platform/application pull request #233
Opened 2020-12-20 23:01 UTC by joeyabou

**IMPORTANT: Please do not create a Pull Request without creating an issue first.**
Please provide enough information so that others can review your pull request:

Explain the **details** for making this change. What existing problem does the pull request solve?

### Test plan (required)
Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes UI.

### Closing issues
List all issues this PR resolves.
- `closes #XXXX` 

### Pre-Merge checklist 
Complete these items before requesting reviews
- [ ] Static Analysis Rules Validated
- [ ] All commits follow naming conventions 

### Sub-tasks Checklist
- [ ] UI Implementation
- [ ] UI Test
- [ ] Backend Implementation
- [ ] Backend Tests
- [ ] Integration Tests
- [ ] System Tests

2020-12-23 17:07 UTC, jonathanp16 approved these changes
Overall looks very solid. I like the use of binding certain classes based on an active boolean, as well as the way you restructured the Jetstream Navlink to fit our needs. Good coverage and no code smells. Good job!

2020-12-28 18:03 UTC, danseremet approved these changes
LGTM!

2020-12-30 19:36 UTC, jonathanp16 requested changes
Looks like there's a merge conflict in the User model

2021-01-06 03:22 UTC, WindOfRussia commented on app/Models/User.php
> +        'can',
by appending the dynamic attribute, we ensure its going to be always available in the frontend user object

2021-01-06 03:23 UTC, WindOfRussia submitted a review, later dismissed
re-approving this as the underlying conflict was resolved

2021-01-06 04:51 UTC, jonathanp16 submitted a review, later dismissed

2021-01-07 16:25 UTC, alexstojda submitted a review, later dismissed
The navbar does not seem to be working as show in the screenshots, see the demo deployment linked to the PR

Additionally please use the application name & logo define in the settings, see https://github.com/CSU-Booking-Platform/application/pull/232

![image](https://user-images.githubusercontent.com/1353716/103916969-0fea3800-50db-11eb-96b3-df5ba3f931fb.png)

2021-01-11 03:39 UTC, Alex-Hayeur submitted a review, later dismissed
The logo is still incorrect as-per Alex's review, his review was discarded by mistake.

2021-01-14 14:26 UTC, alexstojda approved these changes
Thanks for implementing the changes, looks ok to me now.

2021-01-14 14:59 UTC, jonathanp16 submitted a review, later dismissed

2021-01-14 15:33 UTC, alexstojda commented
having a look at the merge issues

2021-01-14 15:55 UTC, alexstojda submitted a review, later dismissed

2021-01-14 16:00 UTC, jonathanp16 submitted a review, later dismissed

2021-01-14 16:44 UTC, alexstojda approved these changes
ok merge issue should be resolved

2021-01-14 16:56 UTC, jonathanp16 approved these changes

2021-01-14 16:57 UTC, merged