feat(#248): Restricting roles from rooms
CSU-Booking-Platform/application pull request #309
Opened 2021-01-17 20:26 UTC by EvanDime

**IMPORTANT: Please do not create a Pull Request without creating an issue first.**
Please provide enough information so that others can review your pull request:
This MR is for adding the feature of limiting access of certain roles from specific rooms. When merged, users who are not able to book certain rooms won't have them appear in their search results or if they manage to get a link to the page, submitting the form will block them form making the booking request. 

### Test plan (required)
Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes UI.

Will make unit tests for new Restrictions relation between room and roles. 
### Closing issues
List all issues this PR resolves.
- `closes #248` 

### Pre-Merge checklist 
Complete these items before requesting reviews
- [ ] Static Analysis Rules Validated
- [ ] All commits follow naming conventions 

### Sub-tasks Checklist
- [ ] UI Implementation
- [ ] UI Test
- [ ] Backend Implementation
- [ ] Backend Tests
- [ ] Integration Tests
- [ ] System Tests
- [ ] Documentation

2021-01-21 03:39 UTC, WindOfRussia requested changes
few small changes but great overall

2021-01-21 03:39 UTC, WindOfRussia commented on routes/web.php
> +    Route::put('room/restrictions/{id}', RestrictionsController::class.'@update')
I believe the approach is now to pass an array of `[controller::class, 'method_name']`

2021-01-21 03:39 UTC, WindOfRussia commented on app/Http/Controllers/BookingRequestController.php
> +            'rooms' => Room::hideUserRestrictions(auth()->user())->get(),
should probably pull user off of $request->user rather than relying on a global method.

2021-01-21 15:21 UTC, KeeganWoods1 reviewed
Code looks great, feature works well, just the unit test to look into and I'll approve

2021-01-23 18:02 UTC, EvanDime commented
> Code looks great, feature works well, just the unit test to look into and I'll approve
@KeeganWoods1 What exactly am i missing as far as unit test is concerned? Last i checked i had 100% coverage testing on all pieces of backend

2021-01-23 18:53 UTC, KeeganWoods1 submitted a review, later dismissed
Everything works, all tests pass!

2021-01-23 19:00 UTC, WindOfRussia requested changes
all good, tests passing but it would be a good idea to split up that massive test into 3 smaller ones

2021-01-23 19:00 UTC, WindOfRussia commented
fyi circleCI is down rn so I was testing locally.

2021-01-23 19:45 UTC, EvanDime commented on tests/Feature/RoomRestrictionsTest.php
> +    public function test_restrictions_controller()
Latest commit has the refactor in place.

2021-01-24 04:14 UTC, WindOfRussia approved these changes

2021-01-24 04:22 UTC, KeeganWoods1 approved these changes

2021-01-24 04:25 UTC, merged