test(#289): AT 289
CSU-Booking-Platform/application pull request #646
Opened 2021-04-07 06:51 UTC by danseremet

view all the documents and forms that have been submitted with a booking request

##### **_IMPORTANT: Always create an issue before a PR and provide enough information so that others can review_**

# AT #289 

This dusk test checks if the reference path that was saved is present in the Vue component.
The testing of opening files is already performed in feature tests.

### Closing issues
##### _List all issues this PR resolves_
- closes #289

### Pre-Merge checklist
##### _Complete these items before requesting reviews_
- [x] Static Analysis Rules Validated
- [x] All commits follow naming conventions

### Sub-tasks Checklist
- [x] UI Implementation
- [x] UI Test
- [x] Integration Tests
- [x] System Tests
- [x] Documentation

2021-04-07 15:47 UTC, EvanDime approved these changes

2021-04-08 00:15 UTC, a-drew requested changes
Test does not validate the attachment of files atm. It only validates that the error message shows up.

2021-04-08 00:15 UTC, a-drew commented on tests/Browser/BookRoomsTest.php
>                  ->assertSee('Please remember to attach a filled out "Bake Sale Form" to the document section')
This test needs to be expanded to cover the file attachment process

2021-04-08 00:18 UTC, a-drew commented on tests/Browser/BookRoomsTest.php
>                  ->assertSee('Please remember to attach a filled out "Bake Sale Form" to the document section')
I'll also note that the `testPromptedToDownloadFormAndAttach()` test seems to cover this functionality already

2021-04-11 23:12 UTC, alexstojda commented
Superseded by #677

2021-04-11 23:12 UTC, closed without merging